version: '2'

services:
  app:
    image: cbsan/popcorn
    restart: always
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev:/dev"
    tty: true
